services:
  fe-dashboard:
    image: fe-dashboard:dev
    container_name: fe-dashboard-dev
    build:
      context: .
    ports:
      - '4173:4173'
    env_file:
      - .env
    restart: unless-stopped
